/* UGPHONE MOD — GitHub Pages + Supabase shared backend */
const cfg=window;
let sb=null,me=null,profileSub=null,chatSub=null,keySub=null,statusSub=null,userSub=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(t){const x=$("toast");if(!x)return;x.textContent=t;x.style.display="block";clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display="none",2500)}
function msg(t){if($("authMsg"))$("authMsg").textContent=t}
function validName(s){return /^[A-Za-z0-9_.-]{3,32}$/.test(s)}
function configured(){return cfg.UG_SUPABASE_URL&&cfg.UG_SUPABASE_ANON_KEY&&!cfg.UG_SUPABASE_URL.includes("YOUR-")&&!cfg.UG_SUPABASE_ANON_KEY.includes("YOUR_")}
async function init(){
 if(!configured()){toast("Hãy cấu hình Supabase trong config.js");return}
 const r=document.createElement("script");r.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";r.onload=async()=>{sb=supabase.createClient(cfg.UG_SUPABASE_URL,cfg.UG_SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});await restoreSession();subscribeRealtime();refreshAll()};document.head.appendChild(r)
}
async function restoreSession(){if(!sb)return;const {data}=await sb.auth.getSession();if(data.session)await loadMe();else me=null}
async function loadMe(){const {data:{user}}=await sb.auth.getUser();if(!user){me=null;return}const {data,error}=await sb.from("profiles").select("*").eq("id",user.id).single();if(error||!data){me=null;return}if(data.banned){await sb.auth.signOut();me=null;toast("Tài khoản đã bị BAN.");return}me=data}
async function register(){const u=$("username")?.value.trim(),email=$("email")?.value.trim().toLowerCase(),p=$("password")?.value||"";if(!validName(u))return msg("Tên tài khoản 3-32 ký tự, chỉ dùng chữ, số, _, -, .");if(!email||!email.includes("@"))return msg("Nhập email hợp lệ.");if(p.length<6)return msg("Mật khẩu phải có ít nhất 6 ký tự.");try{const {data,error}=await sb.auth.signUp({email,password:p,options:{data:{username:u}}});if(error)throw error;if(!data.user)throw new Error("Không tạo được tài khoản.");if(!data.session){msg("Tài khoản đã tạo. Nếu Supabase bật xác nhận email, hãy xác nhận email rồi đăng nhập.");return}await loadMe();msg("Tạo tài khoản thành công.");toast("Đã tạo tài khoản");refreshAll()}catch(e){msg(e.message)}}
async function login(){const u=$("username")?.value.trim(),email=$("email")?.value.trim().toLowerCase(),p=$("password")?.value||"";if(!email||!email.includes("@"))return msg("Nhập email để đăng nhập.");if(!p)return msg("Vui lòng nhập mật khẩu.");try{const {error}=await sb.auth.signInWithPassword({email,password:p});if(error)throw error;await loadMe();if(!me)throw new Error("Không đọc được hồ sơ tài khoản.");msg("Đăng nhập thành công.");toast("Đã đăng nhập");refreshAll()}catch(e){msg(e.message)}}
async function logout(){if(sb)await sb.auth.signOut();me=null;renderProfile();toast("Đã đăng xuất");refreshAll()}
async function claimKey(){if(!me)return toast("Bạn cần đăng nhập.");const {data,error}=await sb.rpc("claim_daily_key");if(error)return toast(error.message);$("keyBox").textContent=data;$ ("keyBox").classList.remove("hidden");navigator.clipboard?.writeText(data).catch(()=>{});toast("Đã nhận KEY hôm nay")}
function renderProfile(){const b=$("profileBox");if(!b)return;if(!me){b.innerHTML="<p>Chưa đăng nhập.</p>";return}b.innerHTML=`${me.avatar?`<img class="avatarLarge" src="${esc(me.avatar)}">`:""}<p><b>${esc(me.username)}</b> ${me.role==="admin"?"👑 Admin":""}</p><input id="avatarFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><button class="primary" onclick="saveAvatar()">LƯU AVATAR</button><button onclick="removeAvatar()">XÓA AVATAR</button>`}
async function saveAvatar(){const f=$("avatarFile")?.files?.[0];if(!f)return toast("Chọn ảnh trước.");if(f.size>512*1024)return toast("Ảnh tối đa 512 KB.");const r=new FileReader();r.onload=async()=>{const {data,error}=await sb.from("profiles").update({avatar:r.result}).eq("id",me.id).select().single();if(error)return toast(error.message);me=data;renderProfile();toast("Đã đổi avatar")};r.readAsDataURL(f)}
async function removeAvatar(){const {data,error}=await sb.from("profiles").update({avatar:""}).eq("id",me.id).select().single();if(error)return toast(error.message);me=data;renderProfile()}
function renderChatMessage(m){const box=$("chatMessages");if(!box)return;const el=document.createElement("div");el.className="chatMsg";el.innerHTML=(m.avatar?`<img class="avatar" src="${esc(m.avatar)}">`:`<div class="avatar">${m.username==="Admin"?"A":"U"}</div>`)+`<div class="chatBody"><b>${esc(m.username)}</b><div>${esc(m.message)}</div></div>`;box.appendChild(el);box.scrollTop=box.scrollHeight}
async function loadChat(){if(!sb)return;const {data,error}=await sb.from("messages").select("id,username,avatar,message,created_at").order("created_at",{ascending:true}).limit(200);if(error)return;const box=$("chatMessages");box.innerHTML="";data.forEach(renderChatMessage);if(!chatSub){chatSub=sb.channel("global-chat").on("postgres_changes",{event:"INSERT",schema:"public",table:"messages"},p=>renderChatMessage(p.new)).subscribe()}}
async function sendChat(){if(!me)return toast("Đăng nhập để chat.");const input=$("chatInput"),text=(input?.value||"").trim();if(!text)return;if(text.length>500)return toast("Tin nhắn tối đa 500 ký tự.");const {error}=await sb.from("messages").insert({user_id:me.id,username:me.username,avatar:me.avatar||"",message:text});if(error)toast(error.message);else input.value=""}
async function refreshStats(){if(!sb)return;const {count:users}=await sb.from("profiles").select("id",{count:"exact",head:true});const {count:keys}=await sb.from("keys").select("id",{count:"exact",head:true}).eq("active",true);if($("onlineCount"))$("onlineCount").textContent="—";if($("stats"))$("stats").textContent=`Tài khoản: ${users??0} • KEY đang bật: ${keys??0}`}
async function adminLogin(){const email=$("adminEmail")?.value.trim().toLowerCase(),p=$("adminPass")?.value||"";if(!email||!p)return toast("Nhập email và mật khẩu Admin.");const {error}=await sb.auth.signInWithPassword({email,password:p});if(error)return toast(error.message);await loadMe();if(!me||me.role!=="admin"){await sb.auth.signOut();me=null;return toast("Tài khoản này không có quyền Admin.")}toast("Đăng nhập Admin thành công");loadAdmin()}
async function adminLogout(){await logout();loadAdmin()}
async function loadAdmin(){const loginBox=$("adminLogin"),panel=$("adminPanel");if(!loginBox||!panel)return;if(!me||me.role!=="admin"){loginBox.classList.remove("hidden");panel.classList.add("hidden");return}loginBox.classList.add("hidden");panel.classList.remove("hidden");const [{count:users},{count:banned},{count:keys}]=await Promise.all([sb.from("profiles").select("id",{count:"exact",head:true}),sb.from("profiles").select("id",{count:"exact",head:true}).eq("banned",true),sb.from("keys").select("id",{count:"exact",head:true})]);$("statUsers").textContent=users??0;$("statBanned").textContent=banned??0;$("statKeys").textContent=keys??0;await renderKeys();await renderUsers();await renderAdminChat();await renderServerState()}
async function renderKeys(){const {data}=await sb.from("keys").select("*").order("date",{ascending:false}).order("created_at",{ascending:false});$("keyList").innerHTML=(data||[]).map(k=>`<div class="keyitem"><span>${esc(k.date)} — <b>${esc(k.key)}</b> — ${k.used}/${k.limit} — ${k.active?"BẬT":"TẮT"}</span><button onclick="toggleKey('${k.id}')">${k.active?"TẮT":"BẬT"}</button></div>`).join("")}
async function renderUsers(){const {data}=await sb.from("profiles").select("*").order("created_at",{ascending:false});$("users").innerHTML=(data||[]).map(u=>`<div class="user ${u.banned?"ban":""}"><span><b>${esc(u.username)}</b> — ${u.banned?"BAN":"OK"}</span><div class="adminBtns"><button onclick="banUser('${u.id}',${!u.banned})">${u.banned?"GỠ BAN":"BAN"}</button></div></div>`).join("")}
async function addKey(){const key=$("newKey")?.value.trim(),date=$("keyDate")?.value,limit=Number($("keyLimit")?.value||999999);if(!key||!date)return toast("Nhập KEY và ngày.");const {error}=await sb.from("keys").insert({key,date,limit});if(error)return toast(error.message);$("newKey").value="";await renderKeys();toast("Đã thêm KEY — mọi máy sẽ thấy ngay")}
async function toggleKey(id){const {data}=await sb.from("keys").select("active").eq("id",id).single();if(!data)return;const {error}=await sb.from("keys").update({active:!data.active}).eq("id",id);if(error)toast(error.message)}
async function banUser(id,banned){const {error}=await sb.from("profiles").update({banned}).eq("id",id);if(error)return toast(error.message);await renderUsers();toast(banned?"Đã BAN — thiết bị của tài khoản sẽ bị đăng xuất khi nhận realtime":"Đã GỠ BAN")}
async function adminBroadcastSend(){const input=$("adminBroadcast"),message=(input?.value||"").trim();if(!message)return;const {error}=await sb.from("messages").insert({user_id:me.id,username:"Admin",avatar:me.avatar||"",message:"📢 "+message});if(error)toast(error.message);else{input.value="";toast("Đã gửi toàn hệ thống")}}
async function renderAdminChat(){const {data}=await sb.from("messages").select("*").order("created_at",{ascending:false}).limit(100);$("adminChat").innerHTML=(data||[]).map(m=>`<div class="chatMsg"><b>${esc(m.username)}</b>: ${esc(m.message)}</div>`).join("")}
async function renderServerState(){const {data}=await sb.from("server_state").select("*").eq("id",1).single();const el=$("apiStatus");if(el)el.textContent=data?`Supabase: OK • Server: ${data.status}`:"Supabase: lỗi"}
async function setServerStatus(status){if(!me||me.role!=="admin")return;const {error}=await sb.from("server_state").update({status}).eq("id",1);if(error)return toast(error.message);toast("Đã đổi trạng thái server")}
async function loadServerBanner(){if(!sb)return;const {data}=await sb.from("server_state").select("*").eq("id",1).single();const b=$("serverStatusBanner");if(!b)return;if(!data||data.status==="normal"){b.hidden=true;return}b.textContent=data.display||"Server đang được bảo trì";b.hidden=false}
function subscribeRealtime(){if(!sb)return;statusSub=sb.channel("server-state").on("postgres_changes",{event:"UPDATE",schema:"public",table:"server_state"},()=>{loadServerBanner();if(me?.role==="admin")renderServerState()}).subscribe();keySub=sb.channel("keys-live").on("postgres_changes",{event:"*",schema:"public",table:"keys"},()=>{refreshStats();if(me?.role==="admin")renderKeys()}).subscribe();userSub=sb.channel("profiles-live").on("postgres_changes",{event:"UPDATE",schema:"public",table:"profiles"},async p=>{if(me&&p.new.id===me.id&&p.new.banned){await sb.auth.signOut();me=null;toast("Tài khoản đã bị BAN.");renderProfile()}if(me?.role==="admin")renderUsers()}).subscribe();}
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));const el=$(id);if(el)el.classList.add("active");if(id==="chat")loadChat();if(id==="admin")loadAdmin();if(id==="auth")renderProfile()}
async function refreshAll(){if(!sb)return;await loadMe();renderProfile();await refreshStats();await loadServerBanner();if($("chat")?.classList.contains("active"))loadChat();if($("admin")?.classList.contains("active"))loadAdmin()}
window.show=show;window.register=register;window.login=login;window.logout=logout;window.claimKey=claimKey;window.saveAvatar=saveAvatar;window.removeAvatar=removeAvatar;window.sendChat=sendChat;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.addKey=addKey;window.toggleKey=toggleKey;window.banUser=banUser;window.adminBroadcastSend=adminBroadcastSend;window.setServerStatus=setServerStatus;
function bootBanner(){const b=document.createElement("div");b.id="serverStatusBanner";b.hidden=true;b.style.cssText="position:fixed;top:0;left:0;right:0;z-index:9999;padding:14px;text-align:center;font-weight:700;background:#222;color:#fff";document.body.appendChild(b)}
bootBanner();$("keyDate").value=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Ho_Chi_Minh"});init();
