/* UGPHONE MOD - shared online frontend */
const API_URL=(window.UG_API_URL||"https://YOUR-UGPHONE-BACKEND.onrender.com/api").replace(/\/$/,"");
const $=id=>document.getElementById(id);
let token=localStorage.getItem("ug_token")||"";
let me=null,adminToken=localStorage.getItem("ug_admin_token")||"";
let poller=null;

function toast(t){const x=$("toast");if(!x)return;x.textContent=t;x.style.display="block";clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.style.display="none",2500)}
function msg(t){if($("authMsg"))$("authMsg").textContent=t}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function api(path,opts={}){const h=new Headers(opts.headers||{});h.set("Content-Type","application/json");if(token)h.set("Authorization","Bearer "+token);return fetch(API_URL+path,{...opts,headers:h}).then(async r=>{let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Phản hồi không hợp lệ");return d})}
function adminApi(path,opts={}){const h=new Headers(opts.headers||{});h.set("Content-Type","application/json");if(adminToken)h.set("Authorization","Bearer "+adminToken);return fetch(API_URL+path,{...opts,headers:h}).then(async r=>{let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||"Phản hồi không hợp lệ");return d})}

function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));const el=$(id);if(el)el.classList.add("active");if(id==="chat")loadChat();if(id==="admin")loadAdmin();if(id==="auth")renderProfile()}
function validName(s){return /^[A-Za-z0-9_.-]{3,32}$/.test(s)}
function register(){const u=$("username")?.value.trim(),p=$("password")?.value||"";if(!validName(u))return msg("Tên tài khoản 3-32 ký tự, chỉ dùng chữ, số, _, -, .");if(p.length<6)return msg("Mật khẩu phải có ít nhất 6 ký tự.");api("/register",{method:"POST",body:JSON.stringify({username:u,password:p})}).then(d=>{token=d.token;localStorage.setItem("ug_token",token);me=d.user;msg("Tạo tài khoản thành công.");toast("Đã tạo tài khoản");refreshAll()}).catch(e=>msg(e.message))}
function login(){const u=$("username")?.value.trim(),p=$("password")?.value||"";api("/login",{method:"POST",body:JSON.stringify({username:u,password:p})}).then(d=>{token=d.token;localStorage.setItem("ug_token",token);me=d.user;msg("Đăng nhập thành công.");toast("Đã đăng nhập");refreshAll()}).catch(e=>msg(e.message))}
function logout(){if(!token)return;api("/logout",{method:"POST"}).catch(()=>{}).finally(()=>{token="";me=null;localStorage.removeItem("ug_token");renderProfile();toast("Đã đăng xuất");refreshAll()})}
async function loadMe(){if(!token){me=null;return}try{me=(await api("/me")).user}catch{token="";localStorage.removeItem("ug_token");me=null}}
async function claimKey(){if(!me)return toast("Bạn cần đăng nhập.");try{const d=await api("/keys/claim",{method:"POST"});$("keyBox").textContent=d.key;$("keyBox").classList.remove("hidden");navigator.clipboard?.writeText(d.key).catch(()=>{});toast("Đã nhận KEY hôm nay");refreshStats()}catch(e){toast(e.message)}}
function renderProfile(){const box=$("profileBox");if(!box)return;if(!me){box.innerHTML="<p>Chưa đăng nhập.</p>";return}box.innerHTML=`${me.avatar?`<img class="avatarLarge" src="${esc(me.avatar)}">`:""}<p><b>${esc(me.username)}</b></p><input id="avatarFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><button class="primary" onclick="saveAvatar()">LƯU AVATAR</button><button onclick="removeAvatar()">XÓA AVATAR</button>`}
async function saveAvatar(){const f=$("avatarFile")?.files?.[0];if(!f)return toast("Chọn ảnh trước.");if(f.size>512*1024)return toast("Ảnh tối đa 512 KB.");if(!/^image\/(png|jpeg|webp|gif)$/.test(f.type))return toast("Chỉ PNG, JPG, WebP hoặc GIF.");const r=new FileReader();r.onload=async()=>{try{const d=await api("/profile/avatar",{method:"POST",body:JSON.stringify({avatar:r.result})});me=d.user;renderProfile();toast("Đã đổi avatar")}catch(e){toast(e.message)}};r.readAsDataURL(f)}
async function removeAvatar(){try{const d=await api("/profile/avatar",{method:"POST",body:JSON.stringify({avatar:""})});me=d.user;renderProfile();toast("Đã xóa avatar")}catch(e){toast(e.message)}}
async function loadChat(){try{const d=await api("/chat");const box=$("chatMessages");box.innerHTML=d.messages.map(m=>`<div class="chatMsg">${m.avatar?`<img class="avatar" src="${esc(m.avatar)}">`:"<div class=\"avatar\">U</div>"}<div class="chatBody"><b>${esc(m.username)}</b><div>${esc(m.message)}</div></div></div>`).join("");box.scrollTop=box.scrollHeight}catch(e){toast(e.message)}}
async function sendChat(){const input=$("chatInput"),text=(input?.value||"").trim();if(!me)return toast("Đăng nhập để chat.");if(!text)return;if(text.length>500)return toast("Tin nhắn tối đa 500 ký tự.");try{await api("/chat",{method:"POST",body:JSON.stringify({message:text})});input.value="";loadChat()}catch(e){toast(e.message)}}
async function refreshStats(){try{const d=await api("/stats");$("onlineCount").textContent=d.online;const s=$("stats");if(s)s.textContent=`Tài khoản: ${d.users} • Online: ${d.online} • KEY: ${d.keys}`}catch{}}
async function adminLogin(){const p=$("adminPass")?.value||"";try{const d=await fetch(API_URL+"/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:p})});const j=await d.json();if(!d.ok)throw new Error(j.error||"Sai mật khẩu Admin.");adminToken=j.token;localStorage.setItem("ug_admin_token",adminToken);toast("Đăng nhập Admin thành công");loadAdmin()}catch(e){toast(e.message)}}
async function adminLogout(){try{await adminApi("/admin/logout",{method:"POST"})}catch{}adminToken="";localStorage.removeItem("ug_admin_token");loadAdmin()}
async function loadAdmin(){const loginBox=$("adminLogin"),panel=$("adminPanel");if(!loginBox||!panel)return;if(!adminToken){loginBox.classList.remove("hidden");panel.classList.add("hidden");return}try{const d=await adminApi("/admin/state");loginBox.classList.add("hidden");panel.classList.remove("hidden");$("statUsers").textContent=d.stats.users;$("statOnline").textContent=d.stats.online;$("statBanned").textContent=d.stats.banned;$("statKeys").textContent=d.stats.keys;renderKeys(d.keys);renderUsers(d.users);$("adminChat").innerHTML=d.messages.map(m=>`<div class="chatMsg">${m.avatar?`<img class="avatar" src="${esc(m.avatar)}">`:""}<div><b>${esc(m.username)}</b>: ${esc(m.message)}</div></div>`).join("")}catch(e){adminToken="";localStorage.removeItem("ug_admin_token");loginBox.classList.remove("hidden");panel.classList.add("hidden");toast(e.message)}}
function renderKeys(keys){$("keyList").innerHTML=keys.map(k=>`<div class="keyitem"><span>${esc(k.date)} — <b>${esc(k.key)}</b> — ${k.used}/${k.limit} — ${k.active?"BẬT":"TẮT"}</span><button onclick="toggleKey('${esc(k.id)}')">${k.active?"TẮT":"BẬT"}</button></div>`).join("")}
function renderUsers(users){$("users").innerHTML=users.map(u=>`<div class="user ${u.banned?"ban":""}"><span><b>${esc(u.username)}</b> — ${u.banned?"BAN":"OK"} — IP: ${esc(u.ip||"")}</span><div class="adminBtns"><button onclick="banUser('${esc(u.id)}')">${u.banned?"GỠ BAN":"BAN"}</button><button class="ipban" onclick="banIP('${encodeURIComponent(u.ip||"")}')">BAN IP</button></div></div>`).join("")}
async function addKey(){const key=$("newKey")?.value.trim(),date=$("keyDate")?.value,limit=Number($("keyLimit")?.value||999999);if(!key)return toast("Nhập KEY.");try{await adminApi("/admin/keys",{method:"POST",body:JSON.stringify({key,date,limit})});$("newKey").value="";loadAdmin();toast("Đã thêm KEY — tất cả máy sẽ thấy")}catch(e){toast(e.message)}}
async function toggleKey(id){try{await adminApi("/admin/keys/"+encodeURIComponent(id),{method:"PATCH",body:JSON.stringify({toggle:true})});loadAdmin()}catch(e){toast(e.message)}}
async function banUser(id){try{await adminApi("/admin/users/"+encodeURIComponent(id)+"/ban",{method:"PATCH"});loadAdmin()}catch(e){toast(e.message)}}
async function banIP(ip){try{await adminApi("/admin/ips/ban",{method:"POST",body:JSON.stringify({ip:decodeURIComponent(ip)})});loadAdmin()}catch(e){toast(e.message)}}
async function refreshAll(){await loadMe();renderProfile();await refreshStats();if($("chat").classList.contains("active"))await loadChat();if($("admin").classList.contains("active"))await loadAdmin()}
setInterval(()=>{refreshStats();if($("chat")?.classList.contains("active"))loadChat()},10000);
window.register=register;window.login=login;window.logout=logout;window.show=show;window.claimKey=claimKey;window.saveAvatar=saveAvatar;window.removeAvatar=removeAvatar;window.sendChat=sendChat;window.adminLogin=adminLogin;window.adminLogout=adminLogout;window.addKey=addKey;window.toggleKey=toggleKey;window.banUser=banUser;window.banIP=banIP;
$("keyDate").value=new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Ho_Chi_Minh"});refreshAll();
